Changes
thok54/Bank-project pull request #3
Opened 2018-09-07 05:07 UTC by thok54

Implemented an "AccountNotFoundException"  replacing the exceptions caused in the CSV Account repository, and dealing with it so the code does not get interrupted when it occurs.
Added a couple of tests checking how CSV Account deals with potential exceptions.

2018-09-07 21:58 UTC, jantpedraza requested changes
Unit Tests are pending, right?

2018-09-07 21:58 UTC, jantpedraza commented on src/main/java/ejercicio/banco/repository/CsvAccountRepository.java
> +                catch(Exception e){}
One question, why do you need to catch here the exception? As far as I can see, here no exception can be thrown, am I right?

2018-09-07 21:58 UTC, jantpedraza commented on src/main/java/ejercicio/banco/repository/CsvAccountRepository.java
> +            in = null;
This would throw a `NullPointerException` in the line 114 in case the `FILENAME` doesn't exist. If the file doesn't exist, what would you do it?

2018-09-07 21:58 UTC, jantpedraza commented on src/main/java/ejercicio/banco/service/PaymentServiceImpl.java
> +                    bestBank.getUsers().get(payments.get(i).getUserId() - 1).setMoney(bestBank.getUsers().get(payments.get(i).getUserId() - 1).getMoney() - payments.get(i).getAmount());
This line is a bit difficult to understand (I know it was here before). Could you refactor it a bit? At least, extracting some variables out of this objects orgy :D

2018-09-08 11:01 UTC, thok54 commented
Added changes. If in=null we get a null bank, which will cascade into more errors when trying to access it. I can try to handle all the possible errors it can produce, but I feel that if the bank information is wrong, the program should either terminate with an error or ask for different specification. 

For some reason, the test fails when I try to use AssertEquals, maybe due to the "delta value"

Now I'm going to watch a disney movie or something, coding overnight always gives me nightmares x)

2018-09-12 20:14 UTC, merged