Changes
thok54/Bank-project pull request #4
Opened 2018-09-13 07:33 UTC by thok54

Still can´t mark directories as Root. Whenever I click on "Mark as...", only option is "Excluded"

2018-09-13 20:58 UTC, jantpedraza requested changes

2018-09-13 20:58 UTC, jantpedraza commented on src/main/java/ejercicio/banco/service/AccountServiceImpl.java
> +    //Store user
What is the point of this comment? The method is super clear, `storeAccount`. 

As general, a good rule for the javadocs is: Only describe what is not clear enough with the method name + the received parameters.

2018-09-13 20:58 UTC, jantpedraza commented on src/test/java/ejercicio/banco/tester/CsvAccountRepositoryTest.java
> +    public void otherTests(){
OMG!! `otherTests()`!!! Never again please :)

Use a proper method for the tests, this is super important.

2018-09-13 23:44 UTC, thok54 commented
Sorry If I have not been answering to each comment individually. By the time I see them, there are various of them so I try to answer them all by uploading the requested changes together.

2018-10-02 03:34 UTC, thok54 commented
I think I am not sure I understand the exercise.

Am I suppose to have a single generate method that can produce either of our 3 objects, or do we want an independent implementation for each of the 3 classes?

Also, I am supposed to tell what kind of item I "have" in order to call the proper method.
What object am I suppose to be checking?

Would it not be much simpler to simply have something like: "generateRandomBank" when I want a random bank?

2018-10-03 21:34 UTC, jantpedraza commented
Te viene bien mañana por la noche un skype y lo hablamos? Sobre las 21:00 hora Málaga. Sino, ve implementando la estructura del buscador y las clases y luego lo vemos.

Enviado desde mi iPhone

> El 2 oct 2018, a las 5:34, Jesus Alvarez Gonzalez <notifications@github.com> escribió:
> 
> I think I am not sure I understand the exercise.
> 
> Am I suppose to have a single generate method that can produce either of our 3 objects, or do we want an independent implementation for each of the 3 classes?
> 
> Also, I am supposed to tell what kind of item I "have" in order to call the proper method.
> What object am I suppose to be checking?
> 
> Would it not be much simpler to simply have something like: "generateRandomBank" when I want a random bank?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-10-03 21:57 UTC, jantpedraza commented
Estoy pensando Jesús, que para simplificar el problema, vamos a generar aleatoriamente los bancos; payments y accounts, pero el buscador sólo va a buscar en nombres de bancos y cuentas, ok? De forma que será un string.

Si ves que el factory no consigues sacarlo, hazlo cómo tu dices y luego vemos el porqué de usar ese patrón.

Enviado desde mi iPhone

> El 3 oct 2018, a las 23:34, Juan Antonio Pedraza Gutiérrez <jantpedraza@gmail.com> escribió:
> 
> Te viene bien mañana por la noche un skype y lo hablamos? Sobre las 21:00 hora Málaga. Sino, ve implementando la estructura del buscador y las clases y luego lo vemos.
> 
> Enviado desde mi iPhone
> 
>> El 2 oct 2018, a las 5:34, Jesus Alvarez Gonzalez <notifications@github.com> escribió:
>> 
>> I think I am not sure I understand the exercise.
>> 
>> Am I suppose to have a single generate method that can produce either of our 3 objects, or do we want an independent implementation for each of the 3 classes?
>> 
>> Also, I am supposed to tell what kind of item I "have" in order to call the proper method.
>> What object am I suppose to be checking?
>> 
>> Would it not be much simpler to simply have something like: "generateRandomBank" when I want a random bank?
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.

2018-10-06 08:55 UTC, jantpedraza approved these changes

2018-10-06 09:10 UTC, merged